//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proje.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class THEATEREntities : DbContext
    {
        public THEATEREntities()
            : base("name=THEATEREntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BAdmin> BAdmin { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TBAbout_us> TBAbout_us { get; set; }
        public virtual DbSet<TBActivity> TBActivity { get; set; }
        public virtual DbSet<TBAnnouncement> TBAnnouncement { get; set; }
        public virtual DbSet<TBContact> TBContact { get; set; }
        public virtual DbSet<TBMembers> TBMembers { get; set; }
        public virtual DbSet<TBMessage> TBMessage { get; set; }
        public virtual DbSet<TBShow> TBShow { get; set; }
        public virtual DbSet<TBstaff_member> TBstaff_member { get; set; }
        public virtual DbSet<TBWriter> TBWriter { get; set; }
    }
}
