//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proje.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBActivity
    {
        public byte ID { get; set; }
        public int Show { get; set; }
        public int Member { get; set; }
        public int staff_member { get; set; }
        public Nullable<System.DateTime> buying_date { get; set; }
        public Nullable<System.DateTime> returning_date { get; set; }
        public Nullable<bool> operation_state { get; set; }
    
        public virtual TBMembers TBMembers { get; set; }
        public virtual TBShow TBShow { get; set; }
        public virtual TBstaff_member TBstaff_member { get; set; }
    }
}
