//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proje.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBAnnouncement
    {
        public byte ID { get; set; }
        public string Header { get; set; }
        public string Contant { get; set; }
        public System.DateTime DateOfAnnouncement { get; set; }
    }
}
