//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proje.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBMessage
    {
        public byte ID { get; set; }
        public string Sender { get; set; }
        public string Receiver { get; set; }
        public string Subject { get; set; }
        public string Contant { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
